# Tomcat
server:
  port: 8081

# Spring
spring:
  application:
    # 应用名称
    name: nft-shop
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nft_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
  type-aliases-package: com.cl.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ipfs:
  url: /ip4/192.168.163.129/tcp/5001
  show-url: 192.168.163.129:8080/ipfs/

